import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai, Podkova } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const podkova = Podkova({ subsets: ["latin"], variable: "--font-inter" });
const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  subsets: ["thai"],
  weight: ["400", "700"],
  variable: "--font-ibm-plex-sans-thai"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${podkova.variable} ${ibmPlexSansThai.variable}`}>
        {children}
      </body>
    </html>
  );
}
